### PR TITLE
Automate font stuff

### PR DESCRIPTION
**Pull request by keveri**
This automates the process of getting fonts from a .txt file to JS.

### CODE REVIEW

**Comment by keveri** [comment]
Might be a good idea to ignore the fonts.js file from the repository.

**Comment by thevangelist** [comment]
Good work.. do you mean excluding fonts.txt?

**Comment by keveri** [comment]
Hmm maybe both as those are user specific files. But that's just a thought.

**Comment by thevangelist** [comment]
That list contains Google fonts available online from here: [worknotes](http://worknotes.scripting.com/february2012/22612ByDw/listOfGoogleFonts) ..so all of them (if not deprecated data) are available for all users. No local fonts are used.

**Pull request merged**
